import type { Metadata } from "next";
import { cookies } from "next/headers";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { ProfileDropdown } from "@/components/profile-dropdown";
import "./../globals.css";

export const metadata: Metadata = {
    title: "Upload Image",
    description: "Generated by create next app",
};

export default async function UploadImageLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const cookieStore = await cookies();
    const defaultOpen = cookieStore.get("sidebar_state")?.value === "true";
    return (
        <SidebarProvider defaultOpen={defaultOpen}>
            <AppSidebar />
            <main className="w-full">
                <div className="flex items-center justify-between">
                    <SidebarTrigger />
                    <ProfileDropdown />
                </div>
                {children}
            </main>
        </SidebarProvider>
    );
}
